config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/recipes/api_call", to: "recipes#api_call"
  resources :recipes, only: [ :index, :show, :new, :create ] do
    resources :ratings, only: [:create ]
    resources :cookbooks, only: [ :create ]
  end

  resources :cookbooks, only: [:index, :destroy]

end

app/models/cookbook.rb
class Cookbook < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
 has_many :recipe_ingredients
 has_many :recipes, through: :recipe_ingredients

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :cookbooks

  validates :title, uniqueness: true

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

  def self.by_ingredient(ingredient_name)
    Recipe.joins(recipe_ingredients: :ingredient).where( 'ingredients.name ILIKE ?', "%#{ingredient_name}%").order("rating DESC")
  end

end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end


end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController

  def index
    if current_user
    @cookbooks = Cookbook.where(user: current_user)
    else
    @cookbooks = []  
    end
  end


  def create
    @cookbook = Cookbook.find_by(recipe_id: params[:recipe_id], user_id: current_user.id)
    if @cookbook
      @cookbook.destroy
      render json: {}
    else
        @cookbook = Cookbook.new
        @user = current_user
        @recipe = Recipe.find(params[:recipe_id])
        @cookbook.recipe = @recipe
        @cookbook.user = @user
        @cookbook.save
          render json: @cookbook
    end
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def create
    @rating = Rating.new(rating_params)
    @user = current_user
    @recipe = Recipe.find(params[:recipe_id])

    @rating.recipe = @recipe
    @rating.user = @user

    if  @rating.save
      redirect_to recipe_path(@recipe)
    else
      render "recipes/show"
    end

  end

  private

  def rating_params
    params.require(:rating).permit(:rating)
  end
end

app/controllers/recipes_controller.rb
require 'json'
require 'open-uri'
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index

    user_ingredients = params[:query].split(" ")
    @user_ingredients = user_ingredients
    @recipes = []
    user_ingredients.each do |ingredient|
      @recipes << Recipe.by_ingredient(ingredient)
    end

    @recipes = @recipes.flatten - [nil]
    @recipes = @recipes.take(10)

  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def show
    @rating = Rating.new
    @cookbook = Cookbook.new
  end

  def api_call
    api_key = "8125a13e97764742a7910c93056f7fed"
    recipes = [];
    @saved_recipes = [];

    url = "https://api.spoonacular.com/recipes/findByIngredients?ingredients=#{params[:query]}&number=5&apiKey=#{api_key}"
    five_recipes = URI.open(url).read
    recipes_ingredients = JSON.parse(five_recipes)

    recipes_ingredients.each do |recipe|
      url = "https://api.spoonacular.com/recipes/#{recipe["id"]}/information?includeNutrition=false&apiKey=#{api_key}"
      one_recipe = URI.open(url).read
      parsed_recipe = JSON.parse(one_recipe)

      recipes.push(parsed_recipe)
    end

    recipes.each do |recipe|
      existing_recipe = Recipe.find_by(title: recipe["title"])
      unless existing_recipe
        new_recipe = Recipe.create!(
          image: recipe["image"],
          title: recipe["title"],
          prep_time: recipe["readyInMinutes"].to_s,
          description: recipe["summary"],
          serving_size: recipe["servings"].to_s,
          rating: recipe["spoonacularScore"].to_i,
          difficulty_level: recipe["readyInMinutes"].to_s,
          steps: recipe["instructions"]
        )

        recipe["extendedIngredients"].each do |ingredient|
          existing_ingredient = Ingredient.find_by(name: ingredient["name"])
          unless existing_ingredient
          existing_ingredient = Ingredient.create!(
            name: ingredient["name"],
            api_response: ingredient["id"]
          )
          end

          if existing_ingredient
          RecipeIngredient.create!(
            amount: ingredient['original'],
            recipe: new_recipe,
            ingredient: existing_ingredient
          )
          end
        end

        @saved_recipes.push(new_recipe)
      end
    end

  end

  private

  def recipe_params
     params.require(:recipe).permit(:comment, :image, :title, :prep_time, :description, :serving_size, :rating, :difficulty_level, :steps, ingredients_attributes: [:id, :name, :_destroy])
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def resource_name
        :user
      end
      def resource
        @user ||= User.new
      end
      def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
      end

end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/cookbooks/index.html.erb
<style>
    body {
        background-color: #F4F4F4;
    }
</style>
<div class="container-fluid mb-5">
    <div class="row ml-4">
        <h1> My Recipes </h1><br>
    </div>
    <% if @cookbooks.count == 0 %>
    <div class="row mx-auto text-center d-flex justify-content-center">
        <br><br>
        <h3 class="text-center">You have not added any recipe in your favorites yet!<br><br>
            Click on <i class="far fa-bookmark mr-2"></i> to add one</h3>
    </div>
    <% end %>

    <div class="row mt-5 ml-3 mr-3">
        <% @cookbooks.each do |cookbook| %>
           <div class="col-lg-12 col-xl-6">
            <article class="postcard postcard-styling">
                <%= link_to recipe_path(cookbook.recipe_id), class: "postcard__img_link" do %>
                <img class="postcard__img" src="<%= Recipe.find(cookbook.recipe_id).image %>" alt="Image Title" />
                <% end %>


                            <div class="postcard_text_container" style="background-color:white">
                                <h1 class="postcard__title mt-4"><a href="<%=recipe_path (cookbook.recipe_id)%>" style="color:black;text-decoration: none;"><%= Recipe.find(cookbook.recipe_id).title.truncate_words(5) %></a></h1>
                                <div class="postcard__bar"></div>
                                <% @descrip = Recipe.find(cookbook.recipe_id).description.truncate_words(25) %>
                                <div class="postcard__preview-txt mb-3" style="color:grey"><%= strip_tags(@descrip) %></div
                                ><br><br>
                                <ul class="postcard__tagbox mb-3">
                                            <li class="tag__item"><i class="fas fa-clock mr-2"></i><%= Recipe.find(cookbook.recipe_id).prep_time %></li>
                                            <li class="tag__item"><i class="fas fa-star mr-2"></i><%= (Recipe.find(cookbook.recipe_id).rating)/20 %> / 5</li>
                                            <% if Recipe.find(cookbook.recipe_id).difficulty_level.to_i >= 45 %>
                                            <li class="tag__item"><i class="fas fa-cookie-bite mr-2"></i>Hard</li>
                                            <% elsif Recipe.find(cookbook.recipe_id).difficulty_level.to_i >= 20 && Recipe.find(cookbook.recipe_id).difficulty_level.to_i < 45 %>
                                            <li class="tag__item"><i class="fas fa-cookie-bite mr-2"></i>Medium</li>
                                            <% else %>
                                            <li class="tag__item"><i class="fas fa-cookie-bite mr-2"></i>Easy</li>
                                            <% end %>
                 
                                     <%= simple_form_for :cookbooks, url: recipe_cookbooks_path(cookbook.recipe_id, user_id: current_user), html: { "data-id": cookbook.recipe_id, class: :selectable, :'data-type' => 'json' } do |f| %>
                                           <button type="submit" class="tag__item" id="button-<%= cookbook.recipe_id %>">
                                             <li style="list-style-type: none"><i class="far fa-bookmark mr-2"></i><span  style="color:black">remove</span></li>
                                            </button>
                                       <%end%>


                    </ul>
                </div>
            </article>
        </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body data-controller="<%=params[:controller] %>" data-action="<%=params[:action] %>" >
<div class="content">
<% if content_for? :nav %>
  <%= content_for :nav %>
<% else %>
   <%= render 'shared/navbar' %>
<% end %>


   
    <%= render 'shared/flashes' %>
  
    <%= yield %>
</div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/_custom_nav.html.erb
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap" rel="stylesheet">

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon " >
  <a href="<%= root_path %>" class="navbar-brand">
  <p class="navbar-text" style="font-family: 'Montserrat', sans-serif;color: #BDA06A; font-size: 2em">Fridgify</p></a>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse w-50 mr-5 d-flex justify-content-end " id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="navbar-nav m-0 d-flex w-100 justify-content-end">
        <div class= "d-flex justify-content-center align-items-center" id="navTitle1">
          <%= link_to "Create your Recipes", "/recipes/new"%>
        </div>
        <div class="d-flex mr-3">
          <li class="nav-item mr-3">
          <%= link_to "My Recipes",   cookbooks_path, class: "nav-link", style: "color: #BDA06A" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars.githubusercontent.com/u/82251803?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        </div>
      <% else %>
        <li class="nav-item">
            <a href="#" data-toggle="modal" data-target="#modal" class="btn btn-info" style="background-color:#BDA06A">Login</a>
           <a href="#" data-toggle="modal" data-target="#modalUp" class="btn btn-info" style="background-color:#BDA06A">Sign up</a>

        </li>
      <% end %>
    </ul>
  </div>
</div>



  <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <%= render "devise/login" %>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="modalUp" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <%= render "devise/signUp" %>
        </div>
      </div>
    </div>
  </div>

app/views/pages/home.html.erb
<% content_for :nav, render('custom_nav') %>


<div class="container-fluid px-0" style="height: 615px">
  <div class="home-video-wrapper">
    <%= cl_video_tag("fridge.mp4", autoplay: :true, loop: :true, mute: :mute, class: "home_video") %>
    <div class="info-welcome">
      <h1 style="font-family: 'Montserrat';color: white;">Hungry?</h1>
      <p class="question" style="font-family: 'Montserrat';color: white">Tell me what's in your fridge, and I'll tell
        you what to cook!</p>
      <div class="searchbar bg-white">
        <div class="mic" id="voice-recognition" >
          <i id="microphone" class="fas fa-microphone btn" hidden></i>
        </div>
        <div class="input-bar">
          <%= form_tag recipes_path, method: :get do %>
          <%= text_field_tag :query, '', class: "form-control border border-white rounded w-100 m-0",  id:"SpeechToText",
               placeholder: "What's in your fridge?", required: true %>
        </div>
        <div class="s-button">
          <%= submit_tag "Search",  class: "btn btn btn-dark rounded-pill",  id: "formButton" %>
          <% end %>
        </div>
      </div>

    </div>
  </div>

</div>

<div class="container-fluid d-flex justify-content-center pt-5" style="background-color: #1d1c21">
  <div class="inf-cards row">
    <div class="inf-card col-4 justify-content-center mt-3">
      <%= cl_image_tag("voice-message_1_vwg72i.png", :width=>70, :crop=>"scale") %>
      <h2 class="">Voice&type input</h2>
      <p class="">Type or tell us what you have on your fridge.</p>
    </div>
    <div div class="inf-card col-4 justify-content-center mt-3">
      <%= cl_image_tag("diet_bgjlq1.png", :width=>70, :crop=>"scale") %>
      <h2>Find "the" recipe</h2>
      <p class="">Exactly with what you have at home.</p>
    </div>
    <div class="inf-card col-4 justify-content-center mt-3">
      <%= cl_image_tag("recipe_a4xzyb.png", :width=>70, :crop=>"scale") %>
      <h2 class="">Create your own</h2>
      <p>Add more recipes to our comunity.</p>
    </div>
  </div>
</div>
<div class="container-fluid pt-5 pb-5" style="background-color: #1d1c21">
  <div id="demo" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="carousel-caption">
          <p>The best web app in the world, I just input what I have on my fridge and it gives me the best recipes I can
            make! </p> <img src="https://res.cloudinary.com/dfy5vakwb/image/upload/v1623356806/pedro_c4byyx.jpg">
          <div id="image-caption">Pedro Ramirez</div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="carousel-caption">
          <p>LIFE SAVER, I dont have time to go out and buy more stuff so I just ask Fridgify to give what they got
            based on the food I have.</p> <img src="https://res.cloudinary.com/dfy5vakwb/image/upload/v1623356806/titch_x7owbj.jpg" class="img-fluid">
          <div id="image-caption">Titch Devvo</div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="carousel-caption">
          <p>Now I dont waste any food, good for the world and good for me, Im also learning how to cook...Thanks
            @Fridgify!!!</p> <img src="https://res.cloudinary.com/dfy5vakwb/image/upload/v1623356806/brayan_c2b32e.jpg" class="img-fluid">
          <div id="image-caption">Brayan Rodriguez</div>
        </div>
      </div>
    </div> <a class="carousel-control-prev" href="#demo" data-slide="prev"> <i class="fas fa-arrow-left pl-5"></i> </a>
    <a class="carousel-control-next" href="#demo" data-slide="next"> <i class='fas fa-arrow-right pr-5'></i> </a>
  </div>
</div>
<script>

</script>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
  <%= f.input :name %>
  <%= link_to_remove_association "remove ingredient", f %>
</div>

app/views/recipes/index.html.erb
<style>
  body {
    background-color: #F4F4F4;
  }
</style>


 <div class="container" id="advanced-search">
   <div class="searchindex bg-white w-100 d-flex justify-content-around p-2" style="width: 75%">
        <div class="mic" id="voice-recognition">
          <i id="microphone" class="fas fa-microphone btn"></i>
        </div>
        <div class="input-bar w-75">
          <%= form_tag recipes_path, method: :get do %>
          <%= text_field_tag :query, '', class: "form-control border border-white rounded w-100 mr-0 pr-0",  id:"SpeechToText",
               placeholder: "What's in your fridge?", required: true %>
        </div>
        <div class="hijodeputa w-25">
          <%= link_to "Advanced Search", recipes_api_call_path(query: params[:query])  %>
        </div>
        <div class="s-button">
          <%= submit_tag "Search",  class: "btn btn btn-dark rounded-pill",  id: "formButton" %>
          <% end %>
        </div>
    </div>

  </div>


  <% if @recipes.count == 0 %>
  <div class="row mx-auto text-center d-flex justify-content-center mt-5">
    <h4 class="mt-6">No results, try our advance search.</h4>
  </div>
  <% end %>


  <div class="row mt-5 ml-3 mr-3">

    <% @recipes.each do |recipe| %>

    <div class="col-lg-12 col-xl-6">
      <article class="postcard postcard-styling">
        <a class="postcard__img_link" href="<%=recipe_path(recipe.id)%>">
          <% if recipe.image.nil? %>
          <img class="postcard__img" src="<%= asset_path('food-404.jpg') %>" alt="Image Title" />
          <% else %>
          <img class="postcard__img" src="<%= recipe.image %>" alt="Image Title" />
          <% end %>
        </a>
        <div class="postcard_text_container" style="background-color:white" id="card-<%= recipe.id %>">
          <h1 class="postcard__title mt-4"><a href="<%=recipe_path(recipe.id)%>"
              style="color:black;text-decoration: none;"><%= recipe.title.truncate_words(5) %></a></h1>
          <div class="postcard__bar"></div>
          <div class="postcard__preview-txt mb-3" style="color:grey">
            <%= strip_tags(recipe.description.truncate_words(25)) %></div><br><br>
          <ul class="postcard__tagbox mb-3">
            <li class="tag__item"><i class="fas fa-clock mr-2"></i><%= recipe.prep_time %></li>
            <li class="tag__item"><i class="fas fa-star mr-2"></i><%= recipe.rating %>&nbsp/ 5</li>
            <% if recipe.difficulty_level.to_i >= 45 %>
            <li class="tag__item"><i class="fas fa-cookie-bite mr-2"></i>Hard</li>
            <% elsif recipe.difficulty_level.to_i >= 20 && recipe.difficulty_level.to_i < 45 %>
            <li class="tag__item"><i class="fas fa-cookie-bite mr-2"></i>Medium</li>
            <% else %>
            <li class="tag__item"><i class="fas fa-cookie-bite mr-2"></i>Easy</li>
            <% end %>

       <% if !current_user.nil? %>
                                 <% if recipe.cookbooks.where(user: current_user).empty?  %>
                                      <%= simple_form_for :cookbooks, url: recipe_cookbooks_path(recipe.id, user_id: current_user), html: { "data-id": recipe.id, class: :selectable, :'data-type' => 'json' } do |f| %>
                                           <button type="submit" class="tag__item" id="button-<%= recipe.id %>">
                                             <li style="list-style-type: none"><i class="far fa-bookmark mr-2"></i><span  style="color:white">save</span></li>
                                            </button>
                                       <%end%>
                                 <% else %>
                                     <%= simple_form_for :cookbooks, url: recipe_cookbooks_path(recipe.id, user_id: current_user), html: { "data-id": recipe.id, class: :selectable, :'data-type' => 'json' } do |f| %>
                                           <button type="submit" class="tag__item" id="button-<%= recipe.id %>">
                                             <li style="list-style-type: none"><i class="far fa-bookmark mr-2"></i><span  style="color:black">saved</span></li>
                                            </button>
                                       <%end%>
                                 <% end %>
                  <% else %>
                  <a href="#" data-toggle="modal" data-target="#modalUp">  <li class="tag__item" style="color:black"><i class="fas fa-user-plus mr-2" ></i><span style="color:white">sign up</span></li> </a>

                <%end%>

          </ul>
        </div>
      </article>
    </div>

    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<style>

a {
   text-decoration:none;
   color: inherit;
}
</style>
  <div class="container" id="advanced-search">
   <div class="searchindex bg-white w-100 d-flex justify-content-around p-2" style="width: 75%">
        <div class="mic" id="voice-recognition">
          <i id="microphone" class="fas fa-microphone btn"></i>
        </div>
        <div class="input-bar w-75">
          <%= form_tag recipes_path, method: :get do %>
          <%= text_field_tag :query, '', class: "form-control border border-white rounded w-100 mr-0 pr-0",  id:"SpeechToText",
               placeholder: "What's in your fridge?", required: true %>
        </div>
        <div class="hijodeputa w-25">
          <%= link_to "Advanced Search", recipes_api_call_path(query: params[:query])  %>
        </div>
        <div class="s-button">
          <%= submit_tag "Search",  class: "btn btn btn-dark rounded-pill",  id: "formButton" %>
          <% end %>
        </div>
    </div>
  </div>


<div class="recipe-wrapper mx-auto" style="max-width: 1100px" >

 <div class="mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= @recipe.image %>'); background-size: cover; border-radius: 30px 30px 0px 0px; ">

            <div class="row d-flex justify-content-end">
            

              <% if !current_user.nil? %>
              <% if @recipe.cookbooks.where(user: current_user).empty?  %>
                <%= simple_form_for :cookbooks, url: recipe_cookbooks_path(@recipe.id, user_id: current_user), html: { "data-id": @recipe.id, class: :selectable, :'data-type' => 'json' } do |f| %>
                  <a type="submit" class="tag__item" id="button-<%= @recipe.id %>">
                <li class="tag__item m-4" style="color:black;font-size: 35px;list-style-type:none; color: white;"><i class="far fa-bookmark mr-2" style="color: white;" ></i></li>
                  </a>
              <%end%>
              <% else %>
              <%= simple_form_for :cookbooks, url: recipe_cookbooks_path(@recipe.id, user_id: current_user), html: { "data-id": @recipe.id, class: :selectable, :'data-type' => 'json' } do |f| %>
                <a type="submit" class="tag__item" id="button-<%= @recipe.id %>">
               <li class="tag__item m-4" style="color:black;font-size: 35px;list-style-type:none; color: white;"><i class="far fa-bookmark mr-2" style="color: white;" ></i></li>
                </a>
              <%end%>
              <% end %>
              <% end %>
            </div>


                    <div class="row d-flex justify-content-center m-3 text-center">
                        <h1 style="color:white"><b> <%= @recipe.title %> </b></h1>
                    </div>

                    <div class="row d-flex justify-content-around mt-5">
            

  <div class="rating-wrapper mb-5">
    <% if !current_user.nil? %>
    <% if  Rating.where(user_id: current_user, recipe_id: @recipe.id).empty? %>
    
     <span style="color:white">My rating</span>&nbsp; <%= simple_form_for([@recipe, @rating], html: { class: "review_form" }) do |f| %>
      <%= f.input :rating, collection: (1..5).to_a, label: false %>
      <% end %>
   

    <% else %>
    <p style="color:white">Thanks for rating this recipe!</p>
    <% end %>
    <% else %>
    <p style="color:white">Login or signup to rate this recipe</p>
    <% end %>

</div>
<div class="rating-wrapper">
      <div id="thisrating" data-rating="<%= @recipe.rating %>">
      <div class="align-items-center">
           <p style="margin: 0px; color:white" class="text-center">Global rating</p>
          <select class="br-widget" id="diplay-rating">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select>
      </div>
    </div>
  </div>
            
                </div></div>
<div class="container-fluid px-0">
                <div class="d-flex info-card">
                  <div class="left-container mr-4"  style="background-color: #BDA06A; border-radius: 0px 0px 30px 30px">
                    <% if @recipe.steps %>
    <div class="recipe-steps">
     <h2>Recipe: step by step</h2>
      <p>
          <%=@recipe.steps.html_safe  %>
      </p>
    </div>
  <% end %>

                  </div>
                    <div class="right-container d-flex justify-content-start">
                      <h2 style="text-align: center">Ingredients</h2>
                      <div class="r-ingredients"style="text-align: left; list-style:none">
              
                          <ul>
                            <p>
                              <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
              
                                <li> <strong> <%=  recipe_ingredient.ingredient.name.capitalize %> :</strong> &nbsp  <%= recipe_ingredient.amount %></li>
                              <% end %>
                            </p>
                          </ul>
                      </div>
              
                      <div class="specs-recipe">
                        <div class="r-spec ">
                          <i class="far fas-show fa-clock" style="font-size: 30px"></i>
                          <p>
                            <%= @recipe.prep_time %> Min
                          </p>
                        </div>
              
                        <div class="r-spec">
                          <i class="fas fas-show fa-tachometer-alt" style="font-size: 30px"></i>
                          <% if @recipe.difficulty_level.to_i >= 45 %>
                          <p> Hard </p>
                          <% elsif @recipe.difficulty_level.to_i >= 20 && @recipe.difficulty_level.to_i < 45 %>
                          <p> Meduim </p>
                          <% else %>
                          <p> Easy </p>
                          <% end %>
                        </div>
              
                        <div class="r-spec">
                          <i class="fas fas-show fa-user" style="font-size: 30px"></i>
                          <p>
                            <%= @recipe.serving_size %> Serving
                          </p>
              
                        </div>
              
                      </div>
                  </div>
                </div>

                    <div class="recipe-steps px-1" style="background-color:white; border-radius:20px"><br>
      <h2>Delicious and nutritious</h2>
        <p style="text-align:justify">
          <%= @recipe.description.html_safe %>
        </p>
    </div>
</div></div>